"""
export_engine.py — Layer 3 Tool
Converts a test plan record into DOCX and PDF files.
SOP: architecture/export_sop.md
"""
import re
from pathlib import Path
from datetime import datetime

BASE_DIR = Path(__file__).parent.parent
EXPORTS_DIR = BASE_DIR / "data" / "exports"
EXPORTS_DIR.mkdir(parents=True, exist_ok=True)

# ─── Markdown Parser (for sections) ──────────────────────────────────────────

def _split_markdown_sections(markdown: str) -> dict:
    """Split the LLM markdown into a dict of {section_name: content}."""
    sections = {}
    current_key = None
    current_content = []

    for line in markdown.split("\n"):
        # Match ## Objective, ## Scope, ## Test Cases
        h2 = re.match(r"^## (.+)", line)
        # Match ### Inclusions, ### Test Environments etc.
        h3 = re.match(r"^### (.+)", line)
        h4 = re.match(r"^#### (.+)", line)
        h1 = re.match(r"^# (.+)", line)

        if h1:
            sections["title"] = h1.group(1).strip()
            current_key = None
            current_content = []
        elif h2:
            if current_key:
                sections[current_key] = "\n".join(current_content).strip()
            current_key = h2.group(1).strip().lower().replace(" ", "_")
            current_content = []
        elif h3 or h4:
            # Keep sub-headers inside parent section content
            if current_key:
                current_content.append(line)
        else:
            if current_key is not None:
                current_content.append(line)

    if current_key:
        sections[current_key] = "\n".join(current_content).strip()

    return sections


# ─── DOCX Export ─────────────────────────────────────────────────────────────

def to_docx(test_plan: dict, output_path: str | None = None) -> str:
    """Generate DOCX from test_plan record. Returns file path."""
    from docx import Document
    from docx.shared import Pt, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    jira_id = test_plan["jira_id"]
    markdown = test_plan["content"]["markdown"]
    sections = _split_markdown_sections(markdown)

    # Allow yielding buffer if output_path strictly not used, 
    # but for local parity we still set a default filename string unless instructed otherwise
    use_buffer = False
    if output_path == "buffer":
        use_buffer = True
    elif not output_path:
        date_str = datetime.now().strftime("%Y%m%d")
        fname = f"{jira_id}_{date_str}.docx"
        output_path = str(EXPORTS_DIR / fname)

    doc = Document()

    # Title
    title_para = doc.add_heading(test_plan.get("title", f"Test Plan — {jira_id}"), level=1)

    meta = doc.add_paragraph(
        f"Generated by {test_plan.get('llm_model', 'LLM')} | "
        f"{_format_date(test_plan.get('generated_at', ''))} | "
        f"{test_plan.get('test_case_count', 0)} Test Cases"
    )
    meta.runs[0].font.color.rgb = RGBColor(0x80, 0x80, 0x80)
    meta.runs[0].font.size = Pt(9)

    # Ordered sections matching the template
    ordered_sections = [
        ("objective", "Objective", 2),
        ("scope", "Scope", 2),
    ]
    sub_sections = [
        ("inclusions", "Inclusions", 3),
        ("exclusion", "Exclusion", 3),
        ("test_environments", "Test Environments", 3),
        ("defect_reporting_procedure", "Defect Reporting Procedure", 3),
        ("test_strategy", "Test Strategy", 3),
        ("test_schedule", "Test Schedule", 3),
        ("test_deliverables", "Test Deliverables", 3),
        ("entry_and_exit_criteria", "Entry and Exit Criteria", 3),
        ("tools", "Tools", 4),
        ("risks_and_mitigations", "Risks and Mitigations", 4),
        ("approvals", "Approvals", 4),
    ]

    full_markdown_lines = markdown.split("\n")
    _write_sections_to_doc(doc, full_markdown_lines)

    # Test Cases section
    tc_list = test_plan["content"].get("test_cases", [])
    if tc_list:
        doc.add_heading("Test Cases", level=2)
        for tc in tc_list:
            _write_test_case_to_doc(doc, tc)

    if use_buffer:
        import io
        buffer = io.BytesIO()
        doc.save(buffer)
        buffer.seek(0)
        return buffer
        
    doc.save(output_path)
    return output_path


def _write_sections_to_doc(doc, lines):
    """Parse markdown lines and write to docx with proper heading levels."""
    from docx.shared import Pt
    skip_tc_section = False

    for line in lines:
        if re.match(r"^## Test Cases", line):
            skip_tc_section = True
            continue
        if skip_tc_section and re.match(r"^### TC-", line):
            continue
        if skip_tc_section:
            continue

        if re.match(r"^# ", line):
            continue  # Already written as title
        elif re.match(r"^## ", line):
            doc.add_heading(line[3:].strip(), level=2)
        elif re.match(r"^### ", line):
            doc.add_heading(line[4:].strip(), level=3)
        elif re.match(r"^#### ", line):
            doc.add_heading(line[5:].strip(), level=4)
        elif re.match(r"^\|", line):
            # Table row — group and write
            _add_table_line(doc, line)
        elif re.match(r"^\*\*(.+)\*\*:", line):
            # Bold key line
            p = doc.add_paragraph()
            parts = re.split(r"(\*\*.+?\*\*)", line)
            for part in parts:
                if part.startswith("**") and part.endswith("**"):
                    run = p.add_run(part[2:-2])
                    run.bold = True
                else:
                    p.add_run(part)
        elif re.match(r"^[-*•] ", line) or re.match(r"^\s+[-*•] ", line):
            p = doc.add_paragraph(line.lstrip("-*• \t"), style="List Bullet")
        elif re.match(r"^\d+\. ", line):
            p = doc.add_paragraph(re.sub(r"^\d+\. ", "", line), style="List Number")
        elif line.strip():
            doc.add_paragraph(_strip_md_bold(line))


def _strip_md_bold(text: str) -> str:
    return re.sub(r"\*\*(.+?)\*\*", r"\1", text)


_pending_table_rows = []
_last_was_table = False


def _add_table_line(doc, line):
    """Accumulate table rows and write when done — simple single-row write for now."""
    cells = [c.strip() for c in line.strip("|").split("|")]
    if all(re.match(r"^[-:]+$", c.replace(" ", "")) for c in cells if c):
        return  # Skip separator row
    table = doc.add_table(rows=1, cols=len(cells))
    table.style = "Table Grid"
    for i, cell_text in enumerate(cells):
        table.cell(0, 0 + i).text = cell_text


def _write_test_case_to_doc(doc, tc: dict):
    from docx.shared import Pt, RGBColor
    doc.add_heading(f"{tc['id']}: {tc['title']}", level=3)
    p = doc.add_paragraph()
    p.add_run("Priority: ").bold = True
    p.add_run(tc.get("priority", ""))
    p.add_run("   Type: ").bold = True
    p.add_run(tc.get("type", ""))

    if tc.get("preconditions"):
        doc.add_paragraph("Preconditions:").runs[0].bold = True
        for item in tc["preconditions"]:
            doc.add_paragraph(item, style="List Bullet")

    if tc.get("steps"):
        doc.add_paragraph("Steps:").runs[0].bold = True
        for item in tc["steps"]:
            doc.add_paragraph(item, style="List Number")

    p2 = doc.add_paragraph()
    p2.add_run("Expected Result: ").bold = True
    p2.add_run(tc.get("expected_result", ""))

    if tc.get("test_data"):
        doc.add_paragraph("Test Data:").runs[0].bold = True
        for k, v in tc["test_data"].items():
            doc.add_paragraph(f"{k}: {v}", style="List Bullet")

    doc.add_paragraph()  # spacing


def _format_date(iso_str: str) -> str:
    try:
        dt = datetime.fromisoformat(iso_str.replace("Z", "+00:00"))
        return dt.strftime("%d %b %Y %H:%M")
    except Exception:
        return iso_str


# ─── PDF Export (reportlab) ──────────────────────────────────────────────────

def to_pdf(test_plan: dict, output_path: str | None = None) -> str:
    """Generate PDF from test_plan record using reportlab. Returns file path."""
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.lib import colors
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
    )
    from reportlab.lib.enums import TA_LEFT, TA_CENTER

    jira_id = test_plan["jira_id"]
    markdown = test_plan["content"]["markdown"]

    use_buffer = False
    if output_path == "buffer":
        use_buffer = True
        import io
        output_target = io.BytesIO()
    elif not output_path:
        date_str = datetime.now().strftime("%Y%m%d")
        fname = f"{jira_id}_{date_str}.pdf"
        output_target = str(EXPORTS_DIR / fname)
    else:
        output_target = output_path

    doc = SimpleDocTemplate(
        output_target,
        pagesize=A4,
        leftMargin=2 * cm,
        rightMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
    )

    styles = getSampleStyleSheet()

    # Custom styles
    CYAN = colors.HexColor("#00C9B1")
    DARK = colors.HexColor("#1A1A2E")

    style_title = ParagraphStyle(
        "CustomTitle", parent=styles["Title"],
        textColor=DARK, fontSize=18, spaceAfter=6,
    )
    style_h2 = ParagraphStyle(
        "H2", parent=styles["Heading2"],
        textColor=CYAN, fontSize=14, spaceBefore=14, spaceAfter=4,
    )
    style_h3 = ParagraphStyle(
        "H3", parent=styles["Heading3"],
        textColor=DARK, fontSize=12, spaceBefore=10, spaceAfter=3,
    )
    style_h4 = ParagraphStyle(
        "H4", parent=styles["Heading4"],
        textColor=DARK, fontSize=11, spaceBefore=8, spaceAfter=2,
    )
    style_body = ParagraphStyle(
        "Body", parent=styles["Normal"],
        fontSize=10, spaceAfter=3, leading=14,
    )
    style_meta = ParagraphStyle(
        "Meta", parent=styles["Normal"],
        textColor=colors.grey, fontSize=8, spaceAfter=12,
    )
    style_bullet = ParagraphStyle(
        "Bullet", parent=styles["Normal"],
        fontSize=10, leftIndent=14, spaceAfter=2,
        bulletIndent=6, leading=14,
    )
    style_tc_title = ParagraphStyle(
        "TCTitle", parent=styles["Heading3"],
        textColor=CYAN, fontSize=11, spaceBefore=10, spaceAfter=3,
    )

    story = []

    # ── Title ──
    story.append(Paragraph(test_plan.get("title", f"Test Plan — {jira_id}"), style_title))
    story.append(Paragraph(
        f"Generated by {test_plan.get('llm_model', 'LLM')} | "
        f"{_format_date(test_plan.get('generated_at', ''))} | "
        f"{test_plan.get('test_case_count', 0)} Test Cases",
        style_meta,
    ))
    story.append(HRFlowable(width="100%", color=CYAN, thickness=1, spaceAfter=10))

    # ── Body (parse markdown lines) ──
    lines = markdown.split("\n")
    skip_tc = False
    i = 0
    table_rows = []

    while i < len(lines):
        line = lines[i]

        if re.match(r"^## Test Cases", line):
            skip_tc = True
            i += 1
            continue
        if skip_tc:
            i += 1
            continue

        if re.match(r"^# ", line):
            i += 1
            continue  # Already written as title

        # Flush any pending table before a non-table line
        if table_rows and not re.match(r"^\|", line):
            story.append(_build_pdf_table(table_rows))
            story.append(Spacer(1, 6))
            table_rows = []

        if re.match(r"^## ", line):
            story.append(Paragraph(line[3:].strip(), style_h2))
        elif re.match(r"^### ", line):
            story.append(Paragraph(line[4:].strip(), style_h3))
        elif re.match(r"^#### ", line):
            story.append(Paragraph(line[5:].strip(), style_h4))
        elif re.match(r"^\|", line):
            cells = [c.strip() for c in line.strip("|").split("|")]
            if not all(re.match(r"^[-:]+$", c.replace(" ", "")) for c in cells if c):
                table_rows.append(cells)
        elif re.match(r"^[-*•] ", line) or re.match(r"^\s+[-*•] ", line):
            text = line.lstrip("-*• \t")
            story.append(Paragraph(f"• {_md_to_pdf(text)}", style_bullet))
        elif re.match(r"^\d+\. ", line):
            text = re.sub(r"^\d+\. ", "", line)
            story.append(Paragraph(f"• {_md_to_pdf(text)}", style_bullet))
        elif line.strip():
            story.append(Paragraph(_md_to_pdf(line), style_body))
        else:
            story.append(Spacer(1, 4))

        i += 1

    # Flush last table
    if table_rows:
        story.append(_build_pdf_table(table_rows))

    # ── Test Cases ──
    tc_list = test_plan["content"].get("test_cases", [])
    if tc_list:
        story.append(HRFlowable(width="100%", color=CYAN, thickness=1, spaceBefore=10))
        story.append(Paragraph("Test Cases", style_h2))

        for tc in tc_list:
            story.append(Paragraph(f"{tc['id']}: {tc['title']}", style_tc_title))

            meta_data = [
                ["Priority", tc.get("priority", ""), "Type", tc.get("type", "")]
            ]
            t = Table(meta_data, colWidths=[3 * cm, 4 * cm, 2.5 * cm, 4 * cm])
            t.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (0, 0), colors.HexColor("#E8F8F5")),
                ("BACKGROUND", (2, 0), (2, 0), colors.HexColor("#E8F8F5")),
                ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("BOX", (0, 0), (-1, -1), 0.5, colors.lightgrey),
                ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.lightgrey),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ]))
            story.append(t)
            story.append(Spacer(1, 4))

            if tc.get("preconditions"):
                story.append(Paragraph("<b>Preconditions:</b>", style_body))
                for item in tc["preconditions"]:
                    story.append(Paragraph(f"• {item}", style_bullet))

            if tc.get("steps"):
                story.append(Paragraph("<b>Steps:</b>", style_body))
                for j, step in enumerate(tc["steps"], 1):
                    story.append(Paragraph(f"{j}. {step}", style_bullet))

            if tc.get("expected_result"):
                story.append(Paragraph(f"<b>Expected Result:</b> {tc['expected_result']}", style_body))

            if tc.get("test_data"):
                story.append(Paragraph("<b>Test Data:</b>", style_body))
                for k, v in tc["test_data"].items():
                    story.append(Paragraph(f"• {k}: {v}", style_bullet))

            story.append(Spacer(1, 8))

    doc.build(story)
    
    if use_buffer:
        output_target.seek(0)
        return output_target
        
    return output_target


def _md_to_pdf(text: str) -> str:
    """Convert basic markdown bold/italic to reportlab XML tags."""
    text = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", text)
    text = re.sub(r"\*(.+?)\*", r"<i>\1</i>", text)
    return text


def _build_pdf_table(rows: list):
    from reportlab.platypus import Table, TableStyle
    from reportlab.lib import colors
    CYAN = colors.HexColor("#00C9B1")

    t = Table(rows)
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#E0FAFA")),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("BOX", (0, 0), (-1, -1), 0.5, colors.grey),
        ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.lightgrey),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
    ]))
    return t
